# build:
# docker build -t sot-dev - < scripts/dockerfile-run-development
#
# run:
# docker run -it --rm -p 3000:3000 -v gems:/usr/local/bundle -v "$PWD":/usr/src/app sot-dev ./scripts/run-development.sh

FROM ruby:2.3.1
VOLUME /usr/local/bundle
WORKDIR /usr/src/app
EXPOSE 3000
